#!/bin/bash

# install the default version of ruby which comes together with the distribution. This is enough for
# setting up the machine. A better version will be installed later with the help of rbenv
sudo apt-get -y install git-core ruby

# install a chef-solo and his helpers
sudo gem install librarian --no-ri --no-rdoc
sudo gem install chef ruby-shadow --no-ri --no-rdoc

# prepare our working directory
cwd=`pwd`
mkdir ~/.solify && cd ~/.solify
git clone "xxx"

# call our local script
./solify

# go to pwd
cd "$cwd"