#!/bin/bash

# just store the current location
cwd=`pwd`

#
# prepare the system if we run the first time
#
if [ ! -e ~/.solify ]; then

    # install the default version of ruby which comes together with the distribution. This is enough for
    # setting up the machine. A better version will be installed later with the help of rbenv
    echo "Installing system packages"
    sudo apt-get -y install git-core ruby > /dev/null

    # install a chef-solo and his helpers
    if [ -z `which librarian-chef` ]; then
        echo "Installing librarian-chef"
        sudo gem install librarian --no-ri --no-rdoc > /dev/null
    fi

    if [ -z `which chef-solo` ]; then
        echo "Installing chef-solo"
        sudo gem install chef ruby-shadow --no-ri --no-rdoc > /dev/null
    fi

    # prepare our working directory
    echo "Preparing filesystem"
    [ ! -e "~/.solify" ] &&  mkdir ~/.solify

fi

# visit our directory
cd ~/.solify

# clone the sources
if [ -e solify ]; then
    echo "Updating github repository"
    cd solify && git pull origin && cd ..
else
    echo "Cloning github repository"
    git clone git://github.com/dei79/solify.git
fi

# call our local script
echo "Start solifying..."
cd solify && ./solify && cd ..

# go to pwd
echo "Done"
cd "$cwd"