#!/bin/bash

# visit the chef directory
cd chef

# download the external cookbooks
sudo librarian-chef install

# do some special fixes before we can start chef-solo
[ -e /etc/chef/ohai_plugins/README ] && sudo rm -f /etc/chef/ohai_plugins/README

# execute chef-solo
sudo chef-solo -c solo.rb

# go up
cd ..
