#!/bin/bash

# install the default version of ruby which comes together with the distribution. This is enough for
# setting up the machine. A better version will be installed later with the help of rbenv
echo "Updating repositories"
sudo apt-get -q update

echo "Installing system packages"
sudo apt-get -q -y install git-core ruby rubygems > /dev/null

# install a chef-solo and his helpers
if [ -z `which librarian-chef` ]; then
    echo "Installing librarian-chef"
    sudo gem install librarian --no-ri --no-rdoc > /dev/null
fi

if [ -z `which chef-solo` ]; then
    echo "Installing chef-solo"
    sudo gem install chef ruby-shadow --no-ri --no-rdoc > /dev/null
fi

# visit the chef directory
cd chef

# download the external cookbooks
echo "Installing or updating external cookbooks"
sudo librarian-chef install

# do some special fixes before we can start chef-solo
echo "Fixing file system"
[ -e /etc/chef/ohai_plugins/README ] && sudo rm -f /etc/chef/ohai_plugins/README

# define the right node file
nodefile="railsapp-node.json"
if [ ! -z $1 ]; then
 nodefile="$1-node.json"
fi
echo "Using the following role configuration: $nodefile"

# execute chef-solo
echo "Running chef-solo"
sudo chef-solo -c solo.rb -j "../roles/$nodefile"

# go up
cd ..
