#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# install the cookbooks we need for rbenv and ruby build
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'
cookbook 'ruby_build'

# install some helpers
cookbook 'openssl'

# we use apache2
cookbook 'apache2'
cookbook 'passenger_apache2'