#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# install the cookbooks we need for rbenv and ruby build
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'
cookbook 'ruby_build'

# we use apache2
cookbook 'apache2'
cookbook 'passenger_apache2'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
